# coding: utf-8
get_ipython().run_line_magic('automagoc', '')
get_ipython().run_line_magic('automagic', '')
get_ipython().run_line_magic('lsmagic', '')
get_ipython().run_line_magic('lsmagic', '')
get_ipython().run_line_magic('ldir', '')
get_ipython().run_line_magic('ldir', 'DATA')
get_ipython().run_line_magic('ldir', '"DATA"')
get_ipython().run_line_magic('ldir', 'DATA/*')
get_ipython().run_line_magic('ldir', 'DATA')
get_ipython().run_line_magic('ldir', '')
get_ipython().run_line_magic('pinfo', 'ldir')
get_ipython().run_line_magic('ls', '')
get_ipython().run_line_magic('ls', 'DATA')
get_ipython().run_line_magic('ls', '')
get_ipython().run_line_magic('lsmagic', '')
get_ipython().run_line_magic('clear', '')
get_ipython().run_line_magic('lsmagic', '')
get_ipython().run_line_magic('env', '')
get_ipython().run_line_magic('env', 'LOGNAME')
get_ipython().run_line_magic('env', 'SCALA_HOME')
get_ipython().run_line_magic('env', 'WOMBAT')
get_ipython().system('hostname')
get_ipython().system('netstat -an | grep ESTAB')
